create table if not exists public.site_news (
    id bigint generated by default as identity primary key,
    title text not null check (char_length(title) between 1 and 160),
    body text not null check (char_length(body) between 1 and 2000),
    publish_at timestamptz not null default now(),
    created_by uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists is_admin boolean not null default false;
alter table public.site_news enable row level security;

grant select on public.site_news to anon, authenticated;
grant insert, update, delete on public.site_news to authenticated;
grant usage, select on sequence public.site_news_id_seq to authenticated;

drop policy if exists "Public can read published news" on public.site_news;
create policy "Public can read published news"
on public.site_news for select
to anon, authenticated
using (publish_at <= now());

drop policy if exists "Admins can create news" on public.site_news;
create policy "Admins can create news"
on public.site_news for insert
to authenticated
with check (
    auth.uid() = created_by
    and exists (
        select 1 from public.profiles
        where user_id = auth.uid() and is_admin = true
    )
);

drop policy if exists "Admins can update news" on public.site_news;
create policy "Admins can update news"
on public.site_news for update
to authenticated
using (exists (
    select 1 from public.profiles
    where user_id = auth.uid() and is_admin = true
))
with check (exists (
    select 1 from public.profiles
    where user_id = auth.uid() and is_admin = true
));

drop policy if exists "Admins can delete news" on public.site_news;
create policy "Admins can delete news"
on public.site_news for delete
to authenticated
using (exists (
    select 1 from public.profiles
    where user_id = auth.uid() and is_admin = true
));
