create table if not exists public.camo_progress (
    user_id uuid primary key references auth.users(id) on delete cascade,
    progress jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

alter table public.camo_progress enable row level security;

grant select, insert, update on public.camo_progress to authenticated;

drop policy if exists "Users can read their own progress" on public.camo_progress;
create policy "Users can read their own progress"
on public.camo_progress for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own progress" on public.camo_progress;
create policy "Users can insert their own progress"
on public.camo_progress for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own progress" on public.camo_progress;
create policy "Users can update their own progress"
on public.camo_progress for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.progress_history (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    completed integer not null default 0,
    recorded_at timestamptz not null default now(),
    unique (user_id, recorded_at)
);

create unique index if not exists progress_history_user_recorded_idx
on public.progress_history (user_id, recorded_at);

alter table public.progress_history enable row level security;
grant select on public.progress_history to anon, authenticated;
grant insert on public.progress_history to authenticated;

drop policy if exists "Users can read their own progress history" on public.progress_history;
create policy "Users can read their own progress history"
on public.progress_history for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert their own progress history" on public.progress_history;
create policy "Users can insert their own progress history"
on public.progress_history for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Public profiles expose progress history" on public.progress_history;
create policy "Public profiles expose progress history"
on public.progress_history for select
to anon, authenticated
using (exists (select 1 from public.profiles where profiles.user_id = progress_history.user_id and (profiles.is_public or auth.uid() = profiles.user_id)));
