create table if not exists public.camo_reports (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete set null,
    type text not null check (type in ('imagen', 'arma', 'nombre', 'otro')),
    game text not null check (char_length(game) between 1 and 80),
    details text not null check (char_length(details) between 1 and 1000),
    created_at timestamptz not null default now()
);

alter table public.camo_reports enable row level security;

grant insert on public.camo_reports to anon, authenticated;

drop policy if exists "Anyone can submit camo reports" on public.camo_reports;
create policy "Anyone can submit camo reports"
    on public.camo_reports for insert
    with check (user_id is null or user_id = auth.uid());
